<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "products"
 *
 * Auto generated by Extension Builder 2014-02-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'multiblog',
	'description' => 'A blog extension for typo3: Complete Frontend Editing of Blogentries, including blog widgets and comment system, multiple blogs in one installation possible. Easy to install and administration. Responsive Design, works perfectly with the extension responsive_template. TYPO3 6.1 or 6.2 required.',
	'category' => 'plugin',
	'author' => 'Klaus Heuer',
	'author_email' => 'klaus.heuer@t3-developer.com',
	'author_company' => 't3-developer.com',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => 'uploads/multiblog/blogbilder',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.5',
	'constraints' => array(
		'depends' => array(
			
			'typo3' => '6.1.00 - 6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>