<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3dev_responsiveTemplate"
 *
 * Auto generated by Extension Builder 2013-02-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Resonsive Template',
	'description' => 'A responsive Template for TYPO3 4.7 / 6.1 ready to use. One Click to install, including three different backend / frontend layouts (based on fluid) and a responsive slider.',
	'category' => 'templates',
	'author' => 'Klaus Heuer',
	'author_email' => 'klaus.heuer@t3-developer.com',
	'author_company' => 't3-developer.com',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => 'uploads/responsivetemplate/slider',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '1.0.4',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3 - 6.1.0',
			'fluid' => '1.3 - 6.1.0',
			'typo3' => '4.7.0 - 6.1.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>