<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "products"
 *
 * Auto generated by Extension Builder 2014-02-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'multiblog',
	'description' => 'A blog extension for TYPO3: including several blog widgets, comment system, facebook, google+ and twitter sharing buttons and seo fields. Fully social individual meta-tags for each post. Works with TYPO3 6.2 and 6.1. Do NOT update old versions of multiblog - actual there is no update script for the new content structure.',
	'category' => 'plugin',
	'author' => 'Klaus Heuer',
	'author_email' => 'klaus.heuer@t3-developer.com',
	'author_company' => 't3-developer.com',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => 'uploads/multiblog/blogbilder',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.6',
	'constraints' => array(
		'depends' => array(
			
			'typo3' => '6.1.00 - 6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>